/ingresso:
  get:
    tags:
      - "Ingresso"
    description: Listar todos os ingressos
    responses:
      200:
        $ref: "#/components/responses/200"
      400:
        $ref: "#/components/responses/400"
      404:
        $ref: "#/components/responses/404"
      500:
        $ref: "#/components/responses/500"
      default:
        $ref: "#/components/responses/default"

  post:
    tags:
      - "Ingresso"
    description: Inserir novos ingressos
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/definitions/ingresso"
    responses:
      200:
        $ref: "#/components/responses/200"
      400:
        $ref: "#/components/responses/400"
      404:
        $ref: "#/components/responses/404"
      500:
        $ref: "#/components/responses/500"
      default:
        $ref: "#/components/responses/default"

definitions:
  ingresso:
    properties:
      valor:
        type: integer
      descricao:
        type: string
    example:
      valor: 13.50
      descricao: Sociedade dos Poetas Mortos
